<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-O34S300" ignored="0" name="Default test" tests="12" failures="1" timestamp="04 Aug 2018 10:49:20 GMT" time="118.619" errors="0">
  <testcase name="VerifyHomePageTitleTest" time="0.01" classname="com.crm.qa.testcases.HomePageTest"/>
  <testcase name="LoginPageTitleTest" time="0.011" classname="com.crm.qa.testcases.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [Free CRM software in the cloud powers sales and customer service] but found [#1 Free CRM software in the cloud for sales and service]">
      <![CDATA[java.lang.AssertionError: expected [Free CRM software in the cloud powers sales and customer service] but found [#1 Free CRM software in the cloud for sales and service]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.crm.qa.testcases.LoginPageTest.LoginPageTitleTest(LoginPageTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LoginPageTitleTest -->
  <testcase name="VerifyContactsPageLabelTest" time="0.037" classname="com.crm.qa.testcases.ContactsPageTest"/>
  <testcase name="VerifyUserNameTest" time="0.098" classname="com.crm.qa.testcases.HomePageTest"/>
  <testcase name="crmLogoImageTest" time="0.082" classname="com.crm.qa.testcases.LoginPageTest"/>
  <testcase name="selectSingleContactsTest" time="0.089" classname="com.crm.qa.testcases.ContactsPageTest"/>
  <testcase name="VerifyClickOnContactsTest" time="0.718" classname="com.crm.qa.testcases.HomePageTest"/>
  <testcase name="loginTest" time="2.459" classname="com.crm.qa.testcases.LoginPageTest"/>
  <testcase name="selectMultipleContactsTest" time="0.189" classname="com.crm.qa.testcases.ContactsPageTest"/>
  <testcase name="ValidateCreateNewContactTest" time="2.54" classname="com.crm.qa.testcases.ContactsPageTest"/>
  <testcase name="ValidateCreateNewContactTest" time="2.341" classname="com.crm.qa.testcases.ContactsPageTest"/>
  <testcase name="ValidateCreateNewContactTest" time="2.058" classname="com.crm.qa.testcases.ContactsPageTest"/>
</testsuite> <!-- Default test -->
